// The ~50 seed glossary terms, written for someone with zero finance
// background ("explain like I'm 15"). Seeded into the database via
// `POST /api/admin/seed`; also served directly in local mock mode.

export interface SeedTerm {
  term: string;
  definition: string;
}

export const GLOSSARY_SEED: SeedTerm[] = [
  { term: "Stock", definition: "A tiny piece of ownership in a company. If you own Apple stock, you literally own a small slice of Apple. When the company does well, your slice usually becomes worth more; when it struggles, it's worth less." },
  { term: "Share", definition: "One unit of stock. Saying you own '10 shares of Tesla' just means you own 10 pieces of the company. 'Stock' and 'shares' are often used interchangeably." },
  { term: "Bond", definition: "A loan you give to a company or government. They pay you interest for borrowing your money and return the full amount on a set date. Bonds are usually steadier but slower-growing than stocks." },
  { term: "ETF", definition: "Short for exchange-traded fund — a basket holding many stocks or bonds that you can buy as a single item. Buying one share of an S&P 500 ETF instantly spreads your money across 500 big companies." },
  { term: "Index Fund", definition: "A fund that automatically copies a market list ('index') like the S&P 500 instead of paying someone to pick stocks. It's a cheap, low-effort way to own the whole market at once." },
  { term: "S&P 500", definition: "A list of 500 of the biggest US companies, used as the main scoreboard for the US stock market. When people say 'the market was up today,' they usually mean the S&P 500 rose." },
  { term: "Dow Jones", definition: "A famous index tracking 30 large, well-known US companies. It's older and narrower than the S&P 500 but still widely quoted in headlines as 'the Dow.'" },
  { term: "Nasdaq", definition: "Both a stock exchange and an index that's heavy on technology companies. When headlines say 'the Nasdaq surged,' it usually means tech stocks had a good day." },
  { term: "Dividend", definition: "A slice of a company's profit paid out to its shareholders, usually every three months. It's like a thank-you check just for owning the stock." },
  { term: "Market Cap", definition: "The total value of a company on the stock market: share price times the number of shares. A $3 trillion market cap means buying every share would cost $3 trillion." },
  { term: "Bull Market", definition: "A long stretch when prices keep rising and investors are optimistic. Memory trick: a bull attacks by thrusting its horns up." },
  { term: "Bear Market", definition: "When prices have fallen 20% or more from their recent high and pessimism rules. Memory trick: a bear attacks by swiping its paws down." },
  { term: "Correction", definition: "A drop of about 10% from a recent market high. Sounds scary, but corrections are normal and happen fairly often — smaller than a bear market." },
  { term: "IPO", definition: "Initial public offering — the day a private company first sells shares to the public and starts trading on a stock exchange. It's how companies 'go public.'" },
  { term: "Earnings Report", definition: "A company's report card, published every three months, showing how much money it made or lost. Stocks often jump or drop sharply right after, depending on whether results beat expectations." },
  { term: "P/E Ratio", definition: "Price-to-earnings ratio — the share price divided by the company's profit per share. It roughly tells you how 'expensive' a stock is: a high P/E means investors are paying a lot for each dollar of profit, usually betting on big future growth." },
  { term: "Volatility", definition: "How wildly prices swing around. High volatility means big, fast moves up and down; low volatility means calm, steady prices. Crypto is famously volatile." },
  { term: "Liquidity", definition: "How easily something can be turned into cash without losing value. Stocks of big companies are very liquid (sold in seconds); a house is not (it takes months)." },
  { term: "Portfolio", definition: "Everything you've invested in, viewed as one collection — your stocks, bonds, funds, crypto, and so on." },
  { term: "Diversification", definition: "Not putting all your eggs in one basket: spreading money across many investments so one bad bet can't wipe you out. It's the closest thing investing has to a free lunch." },
  { term: "Inflation", definition: "When prices across the economy rise over time, so each dollar buys less. 3% inflation means what cost $100 last year now costs about $103. A little is normal; a lot is painful." },
  { term: "Deflation", definition: "The opposite of inflation — prices broadly falling. It sounds nice, but it usually signals a sick economy, because people delay spending and businesses cut jobs." },
  { term: "CPI", definition: "The Consumer Price Index — the government's main inflation gauge. It tracks the price of a giant basket of everyday things (food, rent, gas) and its monthly release regularly moves markets." },
  { term: "Interest Rate", definition: "The price of borrowing money, shown as a percentage. Higher rates make loans and mortgages cost more and make saving pay more; lower rates do the opposite." },
  { term: "Federal Reserve", definition: "America's central bank, usually called 'the Fed.' It sets the key interest rate for the whole economy and tries to keep both inflation and unemployment low. Its decisions move every market on Earth." },
  { term: "Rate Hike", definition: "When a central bank raises its key interest rate, making borrowing more expensive across the economy. It's the classic tool for cooling down inflation — and stock markets often dislike it." },
  { term: "Rate Cut", definition: "When a central bank lowers its key interest rate to make borrowing cheaper and boost the economy. Markets usually cheer, since cheap money helps companies grow." },
  { term: "Basis Point", definition: "One hundredth of a percentage point. If the Fed cuts rates by 25 basis points, that's 0.25%. Finance people say 'bps' (pronounced 'bips') to avoid decimal confusion." },
  { term: "Hawkish", definition: "Describes a central banker leaning toward higher interest rates to fight inflation. The opposite is 'dovish' — favoring lower rates to help growth. Markets parse every Fed speech for hawkish or dovish hints." },
  { term: "Dovish", definition: "Describes a central banker leaning toward lower interest rates to support jobs and growth, even if inflation runs a bit warm. The opposite of hawkish." },
  { term: "Quantitative Easing", definition: "When a central bank creates money to buy bonds, pushing extra cash into the economy to lower long-term rates. Nicknamed 'QE' or 'money printing' — used in emergencies like 2008 and 2020." },
  { term: "Recession", definition: "When the economy shrinks instead of grows for an extended stretch — businesses sell less, layoffs rise, and spending drops. A common shorthand is two consecutive quarters of shrinking GDP." },
  { term: "GDP", definition: "Gross domestic product — the total value of everything a country produces in a year. It's the broadest measure of an economy's size; growing GDP means a growing economy." },
  { term: "Unemployment Rate", definition: "The percentage of people who want a job but can't find one. Released monthly in the US 'jobs report,' it's one of the numbers the Fed watches most closely." },
  { term: "Yield", definition: "The income an investment pays you, as a percentage of its price. A bond paying $5 a year that costs $100 has a 5% yield. When bond prices fall, yields rise — they move in opposite directions." },
  { term: "Treasury", definition: "A bond issued by the US government — considered the safest investment in the world, since the US has always paid its debts. The 10-year Treasury yield is a benchmark that influences mortgages and nearly everything else." },
  { term: "Yield Curve", definition: "A chart of Treasury yields from short-term to long-term. Normally long-term pays more; when short-term pays more instead (an 'inverted' curve), it has historically been a recession warning." },
  { term: "Mortgage Rate", definition: "The interest rate on a home loan. It mostly follows the 10-year Treasury yield, which is why Fed decisions and inflation news end up changing what homebuyers pay each month." },
  { term: "Cryptocurrency", definition: "Digital money that runs on a decentralized network of computers instead of a bank or government. Bitcoin and Ethereum are the biggest. Prices swing hard because value depends heavily on supply and demand." },
  { term: "Bitcoin", definition: "The first and largest cryptocurrency, created in 2009. Only 21 million will ever exist, which is why fans call it 'digital gold' — a scarce asset outside government control." },
  { term: "Ethereum", definition: "The second-largest cryptocurrency and a platform where developers build apps that run automatically via 'smart contracts.' Its currency is called ether (ETH)." },
  { term: "Blockchain", definition: "The technology behind crypto: a shared ledger of transactions copied across thousands of computers, so no single person can secretly alter it. Think of it as a public receipt book everyone can check." },
  { term: "Stablecoin", definition: "A cryptocurrency designed to always be worth a fixed amount, usually $1, by holding real dollars or similar assets in reserve. Traders use them as digital cash within the crypto world." },
  { term: "Altcoin", definition: "Any cryptocurrency that isn't Bitcoin. There are thousands, ranging from serious projects to jokes — quality varies enormously." },
  { term: "Crypto Wallet", definition: "Software (or a small device) that holds the secret keys proving you own your crypto. 'Not your keys, not your coins' means crypto left on an exchange isn't fully under your control." },
  { term: "Short Selling", definition: "Betting that a price will fall: borrow shares, sell them now, buy them back cheaper later, and pocket the difference. Profitable when you're right — but losses are unlimited when the price rises instead." },
  { term: "Hedge Fund", definition: "A lightly regulated investment fund for wealthy investors and institutions that can bet on almost anything — stocks rising, falling, currencies, commodities. Named for 'hedging,' though many take big risks." },
  { term: "Mutual Fund", definition: "A pool of money from many investors, managed by professionals who buy a mix of stocks or bonds. Similar idea to an ETF, but priced once a day and often with higher fees." },
  { term: "401(k)", definition: "A US retirement account through your employer. Money goes in from your paycheck before taxes and grows until retirement, and many employers add free matching money — the closest thing to a guaranteed win in finance." },
  { term: "Compound Interest", definition: "Earning returns on your returns. $1,000 growing 10% becomes $1,100, then the next 10% applies to $1,100, and so on. Over decades this snowball is how ordinary savers build real wealth." },
  { term: "Commodity", definition: "A raw material traded in bulk — oil, gold, wheat, copper. Commodity prices respond to real-world supply and demand, which is why wars and weather move them." },
  { term: "Tariff", definition: "A tax a country charges on imported goods. Tariffs make foreign products more expensive, which can protect local industries but also raise prices for shoppers and spark trade fights that rattle markets." },
  { term: "Bubble", definition: "When prices of something rise far beyond any sensible value because everyone's afraid of missing out — until confidence breaks and prices crash. Famous examples: dot-com stocks in 2000, US housing in 2008." },
];
